data:
  crowd: true
  data_dir: ./data/
model:
  lstm_size: 400
  name: lstm
  word_embedding:
    name_or_path: bert-base-chinese
optim:
  lr: 0.001
  name: Adam
trainer:
  batch_size: 64
  early_stop: true
  epoch_num: 25
  save_after: 0
  save_dir: ./dev/model/
  save_strategy: best
  test_every: 1
vocab:
  min_count:
    words: 1
